spring:
  application.name: turbine
turbine:
  aggregator:
    clusterConfig: default
    # é…ç½®Eurekaä¸­çš„serviceIdåˆ—è¡¨ï¼Œè¡¨æ˜ç›‘æ§å“ªäº›æœåŠ¡ä¸‹ğŸ‘‡
  appConfig: product-view-service-feign
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/